### ISSUE TITLE
Questions about evaluation

### ISSUE THREAD

**Issue by filaPro** [peoplelu/BSNet#1]
Hi @peoplelu ,

Just had a quick look throw the BSNet paper, found it interesting, but still have 2 questions. Can you may be guide me a little bit throw them? Sorry if I'm missing something in my questions.

1. You use ground truth boxes and superpoints (at least for SSTNet, ISBNet, and SPFormer) and mark this evaluation as weakly supervised. But actually at least for ScanNet simply intersecting superpoints with ground truth boxes gives you __exact__ (not approximate) ground truth instance masks. So with such inputs the evaluation becomes fully supervised and should match 100% of the baseline performance. So, the question is do I understand this unfairness correctly?

2.  Can you give me the intuition behind such impressive increase of detection metrics compared to the fully supervised baseline? E.g. 62 mAP50 for ISBNet compared to your 70 mAP50 for ISBNet+BSNet. As I understand, both of these methods don't predict boxes directly, just infer them from the predicted instance masks. And in instance segmentation performance the weakly supervised method is a little lower than fully supervised.

Thanks in advance,
Danila

**Comment by peoplelu** [comment]
Thank you for your attention and questions.
1. There are some **overlapping bounding boxes**, and it's impossible to obtain precise ground truth instance masks for the points within these overlapping bounding boxes. Our paper primarily addresses the assignment issue of these points. Besides， it's important to emphasize that this aspect significantly impacts performance, which can be concluded in Table 3 of ICCV 2023: "GaPro: Box-Supervised 3D Point Cloud Instance Segmentation Using Gaussian Processes as Pseudo Labelers."
2. This is difficult to explain. In fact, when running the baseline GaPro, I was also surprised to observe this phenomenon. I think it is a valuable question worthy of exploration.

**Comment by filaPro** [comment]
Ah, got it. For the small number of superpoints that completely fall into the intersection of boxes the uncertainty remains.

Thanks for quick reply. Have a nice day:)
