### ISSUE TITLE
About Pretrained

### ISSUE THREAD

**Issue by trandangtrungduc** [peoplelu/BSNet#3]
Hi @peoplelu,

Your research is quite interesting and I have just taken a look at it. My question is:
 Do you use 'pretrained' from SSTNet for training your model? If so, I'm not sure whether the use of  'pretrained' from a trained model with fully supervised behavior is fair for a weakly supervised task?

Thank you in advance.

**Comment by peoplelu** [comment]
Thank you for your interest! We retrained the SSTNet with the pseudo labels generated by our pseudo labeler, which is the same as Gapro(https://github.com/VinAIResearch/GaPro/issues/1).  You can also use the pretrained weight in  https://github.com/VinAIResearch/GaPro/issues/1.

**Comment by trandangtrungduc** [comment]
I got it.
Thank you for your quick response.
